services:
  postgres:
    image: 'postgres:16'
    environment:
      - 'POSTGRES_DB=sahabat_quran_db'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=dev2330'
    ports:
      - '5432:5432'
    volumes:
      - ./db-sahabatquran:/var/lib/postgresql/data
